### ISSUE TITLE
Add k8s recommended label app.kubernetes.io/version 

### ISSUE THREAD

**Issue by wlfghdr** [keptn/examples#103]
Additional to labels given with https://github.com/keptn/examples/issues/91 
and according to https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ the label app.kubernetes.io/version should also be added.
"The current version of the application (e.g., a semantic version, revision hash, etc.)"

**Comment by christian-kreuzberger-dtx** [comment]
# Definition of Done

- [ ] Add the version label to our carts and carts-db example (e.g., use the docker image tag)
- [ ] Try out the updated carts / carts-db example with Keptn 0.6.2 and manually check the pods/deployments on those labels
- [ ] If possible, also update the unleash-server example (or create a follow-up issue)
- [ ] If possible, also update the simplenodeservice example (or create a follow-up issue)

**Comment by jetzlstorfer** [comment]
It would be great if the keptn CLI can check during onboarding if the labels are set in the Helm chart. It does not necessarily have to block the chart to be onboard but give the user a warning that it should be included.

**Comment by christian-kreuzberger-dtx** [comment]
This is a great idea for the cli. We should also document this.

Let's focus on updating our examples in this issue. For the implementation part in the CLI I have created a separate issue in the keptn/keptn repo: https://github.com/keptn/keptn/issues/1958

**Comment by grabnerandi** [comment]
Implemented this with #106 
The way it was done is to look at the version part of the image, e.g: carts:0.1.2 becomes 0.1.2
I've done this with the split function and then also use default in case there is no version information in tag:
`app.kubernetes.io/version: {{ (split ":" .Values.image)._1 | default "latest" }}`

Dynatrace is succesfully showing this label. And - once Dynatrace uses these labels for true version awareness we should see these 3 versions in 3 separate dynatrace service instances. right now these labels show up accumulated on a single service
![image](https://user-images.githubusercontent.com/675886/86240973-64e44900-bba2-11ea-86c4-72221c656c1e.png)

**Comment by christian-kreuzberger-dtx** [comment]
Closed via #106
