### ISSUE TITLE
Script to deploy dynatrace oneagent fails on GKE

### ISSUE THREAD

**Issue by warber** [keptn/examples#156]
Followed the steps in [this](https://deploy-preview-112--keptn-tutorials.netlify.app/tutorials/keptn-full-tour-dynatrace-08/index.html?index=..%2F..keptn08x#9) tutorial to install _dynatrac oneagent_ on a _GKE_ cluster.

The script failed at deploying the _oneagent daemonset_.

Logs from the _daemonset_:

```
10:07:27 Warning: Cannot change permissions of /mnt/host_root/opt directory to u+rwx,g+rx,o+rx: chmod: /mnt/host_root/opt: Read-only file system
10:07:27 Warning: Cannot create /mnt/host_root/opt/dynatrace/oneagent directory: mkdir: can't create directory '/mnt/host_root/opt/dynatrace/': Read-only file system
```

As stated [here](https://www.dynatrace.com/support/help/technology-support/cloud-platforms/kubernetes/deploy-oneagent-k8/#expand-3187anthos-and-gke), the custom resource definition for _oneagent_ needs to be configured with an additional environment variable:

```
env:
 - name: ONEAGENT_ENABLE_VOLUME_STORAGE
   value: "true"

```

Tasks:
- [ ] Extend [`deploy_dynatrace_oneagent.sh`](https://github.com/keptn/examples/blob/master/dynatrace-oneagent/deploy-dynatrace-oneagent.sh) to set the environment variable above when needed

**Comment by christian-kreuzberger-dtx** [comment]
This is no longer an issue, as it is handled by Dynatrace OneAgent installation directly.
See https://github.com/keptn/tutorials/issues/119 for details.
