### ISSUE TITLE
configure-istio.sh fails due to updated k8s networking api version in manifest

### ISSUE THREAD

**Issue by warber** [keptn/examples#177]
While following the Full Tour Keptn Tutorials, step 6 (configuring istio) failed with the following error:

``` 
error: error validating "STDIN": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): 
unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]; if you choose to ignore these errors, turn validation off with --validate=false
``` 

The error was most likely introduced by updating the k8s networking api version in the ingress manifest: https://github.com/keptn/examples/pull/174/files

**Comment by mowies** [comment]
We can safely revert this API to `networking.k8s.io/v1beta1` and still support the latest k8s versions. `networking.k8s.io/v1beta1` is deprecated now but it will be removed in. k8s v1.22 which is not even GA yet :)

Refernence: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122
