### ISSUE TITLE
Quickstart Step 5: multi-stage delivery with evaluation using prometheus fails for the wrong reason

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/examples#203]
I just followed the quickstart as described here:
https://keptn.sh/docs/quickstart/

Primarily the step 5, which is
```
curl -SL https://raw.githubusercontent.com/keptn/examples/master/quickstart/multistage-delivery.sh | bash
```

I ended up having one delivery that worked, and one that did not work (which is according to the plan).

However, the second delivery failed with the following result (tried using Keptn 0.10.0-next.2):

![image](https://user-images.githubusercontent.com/56065213/140055948-92ce8d8e-969c-4b5b-817a-c9f77beb2762.png)

Based on the source code and the information I was provided, I would expect that this example fails because of the "HTTP Response Time" being over 200 ms, and not the go-routines.

FYI, this is the evaluation of the first run:
![image](https://user-images.githubusercontent.com/56065213/140056099-4f84e2ea-38a3-45e8-8355-b198b2919a14.png)

# Tasks

- [ ] Evaluation in multi-stage delivery should fail because of response time
- [ ] Investigate why go-routines fail - this number should be rather static, right?

**Comment by TannerGabriel** [comment]
This should already be fixed by #199.

**Comment by christian-kreuzberger-dtx** [comment]
No, it's not :)
![image](https://user-images.githubusercontent.com/56065213/141313121-8f639cdf-a875-4125-9dad-b0ed6a580169.png)

**Comment by TannerGabriel** [comment]
Are you sure that you are using the correct podtatohead image because the current delay of the slow build is [400ms](https://github.com/jetzlstorfer/podtato-head/blob/main/podtato-server/podtatoserver.go#L83) and not the 200ms that are shown in your image? Also, the [go routines](https://github.com/jetzlstorfer/podtato-head/blob/main/podtato-server/podtatoserver.go#L84) are supposed to fail in the slow build.

**Comment by christian-kreuzberger-dtx** [comment]
Now that we have switched to another podtato-head image in https://github.com/keptn/examples/pull/214, I'll close this.
