### ISSUE TITLE
DT_TAGS Needs [Environment] SLI Definition

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/examples#92]
@christian-kreuzberger-dtx [This SLI file](https://github.com/keptn/examples/blob/45879bd4a4585fc90da1f1654e99cfc2c4d54694/onboarding-carts/sli-config-dynatrace-no-deployment-tag.yaml) works for manual and autotag rules but keptn will fail if using `DT_TAGS` as the tag actually becomes `[Environment]keptn_project:sockshop`.

So if using DT_TAGS the SLI file should be:
```
---
spec_version: '1.0'
indicators:
  throughput: "builtin:service.requestCount.total:merge(0):sum?scope=tag([Environment]keptn_project:$PROJECT),tag([Environment]keptn_stage:$STAGE),tag([Environment]keptn_service:$SERVICE)"
...
```
https://github.com/keptn/examples/blob/45879bd4a4585fc90da1f1654e99cfc2c4d54694/onboarding-carts/sli-config-dynatrace-no-deployment-tag.yaml#L4

The docs should also be adjusted to clarify this: See `Note 2: An alternative option is to use the environment variable DT_TAGS, which will automatically convert the passed values into tags:` (line 123) [here](https://raw.githubusercontent.com/keptn/keptn.github.io/master/content/docs/0.6.0/usecases/quality-gates/index.md).

**Comment by Dynatrace-Adam-Gardner** [comment]
Perhaps this would also make a good Dynatrace enhancement? (That the v2 API ignores that portion of the tag content and instead, just looks at the `K/V`. It would undoubtedly make the DT API easier to work with.

**Comment by jetzlstorfer** [comment]
Using DT_TAGS is actually not the preferred way how to use tags in Dynatrace. The preferred way is to use CUSTOM_PROPS. 
I would suggest to not add the DT_TAGS section to the Keptn documentation as it would emphasize something that is not preferred. What are your ideas?

**Comment by Dynatrace-Adam-Gardner** [comment]
OK, re-reading [this page](https://www.dynatrace.com/support/help/how-to-use-dynatrace/tags-and-metadata/setup/define-tags-based-on-environment-variables/) (IMO it could be worded differently to highlight the strong preference for `DT_CUSTOM_PROP` and use of `DT_TAGS` as a fallback.

However, that aside, the keptn documentation could just be slightly tweaked to highlight that using metadata is considered a best practice and that `DT_TAGS` should only be used as a last case solution
